spring:
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
  freemarker:
    cache: false  
  thymeleaf:
    cache: false  
#  freemarker:
#    allow-request-override: false
#    cache: false
#    check-template-location: true
#    charset: UTF-8
#    content-type: text/html; charset=utf-8
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: false
#    suffix: .ftl
#    template-loader-path: classpath:/templates
  
